[build]
builder = "nixpacks"

[build.nixpacks]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
